# Generated by Django 5.2.17 on 2026-09-28 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wallpapers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallpaper",
            old_name="image_url",
            new_name="image",
        ),
    ]
