# Generated by Django 5.2.17 on 2026-09-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallpapers", "0002_rename_image_url_wallpaper_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallpaper",
            name="image",
            field=models.ImageField(max_length=255, upload_to="wallpapers/"),
        ),
    ]
